#!/usr/bin/env python3
"""
Sync projects from local CSV to frontend data file.

This bypasses Notion API and uses data/projects_import.csv as the CMS.

Usage:
  python local_sync.py
"""

import csv
import json
from datetime import datetime
from pathlib import Path

CSV_FILE = Path(__file__).parent.parent / "data" / "projects_import.csv"
OUTPUT_FILE = Path(__file__).parent.parent / "frontend" / "lib" / "generated-data.ts"

DISTRICT_MAP = {
    "光影剧场": "theater",
    "远行竞技场": "arena",
    "高级画廊": "gallery",
    "记忆高塔": "tower",
    "慢闪档案馆": "archive",
}


def slugify(name: str) -> str:
    """Generate a simple slug from a project name."""
    slug = (
        name.lower()
        .replace(" ", "-")
        .replace("·", "-")
        .replace("/", "-")
        .replace("_", "-")
    )
    slug = "".join(c for c in slug if c.isalnum() or c == "-").strip("-")[:60]
    return slug or "project"


def row_to_project(row: dict) -> dict:
    """Convert a CSV row to our project format."""
    title = row.get("Name", "").strip() or "未命名项目"
    slug = row.get("Slug", "").strip() or slugify(title)
    district = row.get("District", "").strip()
    district_slug = DISTRICT_MAP.get(district, district or "arena")

    tags = [t.strip() for t in row.get("Tags", "").split(",") if t.strip()]

    year_str = row.get("Year", "").strip()
    try:
        year = int(year_str)
    except ValueError:
        year = datetime.now().year

    return {
        "id": slug,
        "title": title,
        "slug": slug,
        "districtSlug": district_slug,
        "location": row.get("Location", "").strip(),
        "summary": row.get("Summary", "").strip(),
        "description": row.get("Description", "").strip() or row.get("Summary", "").strip(),
        "tags": tags,
        "year": year,
        "assets": [],
        "xiaohongshu": row.get("Xiaohongshu", "").strip(),
        "douyin": row.get("Douyin", "").strip(),
    }


def load_projects_from_csv() -> list:
    """Load projects from CSV file."""
    if not CSV_FILE.exists():
        print(f"Error: CSV file not found: {CSV_FILE}")
        return []

    projects = []
    with CSV_FILE.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            project = row_to_project(row)
            if project["title"] and project["title"] != "未命名项目":
                projects.append(project)

    return projects


def write_typescript_data(projects: list):
    """Write projects to frontend TypeScript data file."""
    data = {
        "projects": projects,
        "generatedAt": datetime.now().isoformat(),
        "source": "local-csv",
    }

    json_str = json.dumps(data, ensure_ascii=False, indent=2)

    ts_content = f"""// Auto-generated by backend/local_sync.py
// Do not edit manually. Run local_sync.py to regenerate.

import {{ Project }} from "@/types";

export const generatedProjects: {{ projects: Project[]; generatedAt: string; source: string }} = {json_str};
"""

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(ts_content, encoding="utf-8")
    print(f"Generated: {OUTPUT_FILE}")
    print(f"Total projects: {len(projects)}")


def main():
    projects = load_projects_from_csv()
    write_typescript_data(projects)

    print("\nProjects from CSV:")
    for p in projects:
        print(f"  - {p['title']} ({p['districtSlug']}, {p['year']})")


if __name__ == "__main__":
    main()
