#!/usr/bin/env python3
"""
Sync projects from Notion database to frontend data file.

Usage:
  python notion_sync.py

Requires environment variables:
  NOTION_TOKEN=<your integration token>
  NOTION_DATABASE_ID=<your database id>
"""

import json
import os
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from notion_client import Client

# Load environment variables from project root .env file
project_root = Path(__file__).parent.parent
load_dotenv(project_root / ".env")


def paginated_query(notion: Client, database_id: str, start_cursor=None):
    """Paginate through a Notion database query."""
    kwargs = {
        "database_id": database_id,
        "sorts": [{"property": "Year", "direction": "descending"}],
    }
    if start_cursor:
        kwargs["start_cursor"] = start_cursor

    return notion.databases.query(**kwargs)

OUTPUT_FILE = Path(__file__).parent.parent / "frontend" / "lib" / "generated-data.ts"


def get_rich_text(prop: dict) -> str:
    """Extract plain text from a Notion rich_text property."""
    parts = prop.get("rich_text", [])
    return "".join(part.get("plain_text", "") for part in parts).strip()


def get_title(prop: dict) -> str:
    """Extract plain text from a Notion title property."""
    parts = prop.get("title", [])
    return "".join(part.get("plain_text", "") for part in parts).strip()


def get_select(prop: dict) -> str:
    """Extract name from a Notion select property."""
    select = prop.get("select")
    return select.get("name", "").strip() if select else ""


def get_number(prop: dict) -> int:
    """Extract number from a Notion number property."""
    return int(prop.get("number") or 0)


def get_multi_select(prop: dict) -> list:
    """Extract names from a Notion multi_select property."""
    return [item.get("name", "").strip() for item in prop.get("multi_select", [])]


def notion_to_project(page: dict) -> dict:
    """Convert a Notion page to our project format."""
    props = page.get("properties", {})

    title = get_title(props.get("Name", {})) or "未命名项目"
    slug = get_rich_text(props.get("Slug", {}))
    if not slug:
        # Generate simple slug from title
        slug = (
            title.lower()
            .replace(" ", "-")
            .replace("·", "-")
            .replace("/", "-")
            .replace("_", "-")
        )
        slug = "".join(c for c in slug if c.isalnum() or c == "-").strip("-")[:60]

    district = get_select(props.get("District", {})).lower()
    district_map = {
        "光影剧场": "theater",
        "远行竞技场": "arena",
        "高级画廊": "gallery",
        "记忆高塔": "tower",
        "慢闪档案馆": "archive",
    }
    district_slug = district_map.get(district, district or "arena")

    project = {
        "id": slug,
        "title": title,
        "slug": slug,
        "districtSlug": district_slug,
        "location": get_rich_text(props.get("Location", {})),
        "summary": get_rich_text(props.get("Summary", {})),
        "description": get_rich_text(props.get("Description", {})) or get_rich_text(
            props.get("Summary", {})
        ),
        "tags": get_multi_select(props.get("Tags", {})),
        "year": get_number(props.get("Year", {})),
        "assets": [],
    }

    return project


def fetch_projects(notion: Client, database_id: str) -> list:
    """Fetch all projects from Notion database."""
    projects = []
    has_more = True
    start_cursor = None

    while has_more:
        response = paginated_query(notion, database_id, start_cursor)

        for page in response.get("results", []):
            try:
                project = notion_to_project(page)
                if project["title"]:
                    projects.append(project)
            except Exception as e:
                print(f"Warning: failed to parse page {page.get('id')}: {e}")

        has_more = response.get("has_more", False)
        start_cursor = response.get("next_cursor")

    return projects


def write_typescript_data(projects: list):
    """Write projects to frontend TypeScript data file."""
    data = {
        "projects": projects,
        "generatedAt": datetime.now().isoformat(),
        "source": "notion",
    }

    json_str = json.dumps(data, ensure_ascii=False, indent=2)

    ts_content = f"""// Auto-generated by backend/notion_sync.py
// Do not edit manually. Run notion_sync.py to regenerate.

import {{ Project }} from "@/types";

export const generatedProjects: {{ projects: Project[]; generatedAt: string; source: string }} = {json_str};
"""

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(ts_content, encoding="utf-8")
    print(f"Generated: {OUTPUT_FILE}")
    print(f"Total projects: {len(projects)}")


def main():
    token = os.environ.get("NOTION_TOKEN")
    database_id = os.environ.get("NOTION_DATABASE_ID")

    if not token or not database_id:
        print("Error: NOTION_TOKEN and NOTION_DATABASE_ID must be set in environment.")
        print("Create a .env file in the project root with:")
        print("  NOTION_TOKEN=secret_xxx")
        print("  NOTION_DATABASE_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
        return

    notion = Client(auth=token)
    projects = fetch_projects(notion, database_id)
    write_typescript_data(projects)

    print("\nProjects from Notion:")
    for p in projects:
        print(f"  - {p['title']} ({p['districtSlug']}, {p['year']})")


if __name__ == "__main__":
    main()
