// Auto-generated by backend/local_sync.py
// Do not edit manually. Run local_sync.py to regenerate.

import { Project } from "@/types";

export const generatedProjects: { projects: Project[]; generatedAt: string; source: string } = {
  "projects": [
    {
      "id": "singapore-future-city",
      "title": "新加坡 · 未来生态之城研学",
      "slug": "singapore-future-city",
      "districtSlug": "arena",
      "location": "新加坡",
      "summary": "新加坡未来城市设计 PBL 研学项目，包含课程任务、调研表单与营前手册。",
      "description": "带队参与新加坡科技文化双语交流项目，围绕「未来生态之城」主题开展 PBL 研学。学生通过实地考察新加坡的城市规划、生态建筑与水资源管理系统，完成未来城市设计方案。",
      "tags": [
        "PBL",
        "未来城市",
        "双语研学",
        "带队",
        "生态设计"
      ],
      "year": 2026,
      "assets": [],
      "xiaohongshu": "",
      "douyin": ""
    },
    {
      "id": "uk-harry-potter-academy",
      "title": "英国 · 哈利波特魔法学院",
      "slug": "uk-harry-potter-academy",
      "districtSlug": "arena",
      "location": "英国",
      "summary": "以哈利波特魔法学院为主题的学院分组测试游戏版夏校。",
      "description": "设计并执行英国哈利波特主题夏校，将学院分组、魔法课程、解谜任务与英国文化探访结合。负责营前手册、游戏机制设计、营中活动执行与复盘。",
      "tags": [
        "夏校",
        "游戏化",
        "学院制",
        "英国文化",
        "课程设计"
      ],
      "year": 2025,
      "assets": [],
      "xiaohongshu": "",
      "douyin": ""
    },
    {
      "id": "finland-sisu-aurora",
      "title": "芬兰 · SISU 极光挑战营",
      "slug": "finland-sisu-aurora",
      "districtSlug": "arena",
      "location": "芬兰",
      "summary": "北欧极地研学，聚焦 SISU 精神、自然教育与反思圈文化。",
      "description": "筹备芬兰 SISU 极光挑战营，涵盖极光观测、雪地活动、芬兰教育体验与晚间反思圈。负责行程设计、供应商尽调、营前说明会与安全管理。",
      "tags": [
        "北欧",
        "极光",
        "自然教育",
        "SISU",
        "反思圈"
      ],
      "year": 2026,
      "assets": [],
      "xiaohongshu": "",
      "douyin": ""
    },
    {
      "id": "hongkong-shenzhen-growth",
      "title": "港深 · 成长生态评估体系",
      "slug": "hongkong-shenzhen-growth",
      "districtSlug": "arena",
      "location": "香港 / 深圳",
      "summary": "港深研学项目的成长生态评估体系与全流程管理框架设计。",
      "description": "参与港深研学项目开发，搭建成长生态评估体系、研学带队全流程管理框架与场景评估方案。覆盖行前准备、营中执行、复盘沉淀全链路。",
      "tags": [
        "评估体系",
        "项目管理",
        "港深",
        "带队",
        "课程研发"
      ],
      "year": 2026,
      "assets": [],
      "xiaohongshu": "",
      "douyin": ""
    },
    {
      "id": "chiangmai-artist-market",
      "title": "清迈 · 艺术家市集考察",
      "slug": "chiangmai-artist-market",
      "districtSlug": "gallery",
      "location": "清迈",
      "summary": "清迈艺术家市集与文创商业形态的实地考察记录。",
      "description": "考察清迈艺术家市集、文创街区与独立设计师生态，记录市集运营模式、产品定位与空间氛围。思考艺术商业化的可能性。",
      "tags": [
        "市集",
        "文创",
        "艺术家",
        "商业考察",
        "清迈"
      ],
      "year": 2025,
      "assets": [],
      "xiaohongshu": "",
      "douyin": ""
    }
  ],
  "generatedAt": "2026-07-13T22:55:39.603796",
  "source": "local-csv"
};
